### ISSUE TITLE
Finance Advisor

### ISSUE THREAD

**Issue by zyonwee** [LunarEclipz/OOPP-Slazz#14]

**Comment by LunarEclipz** [comment]
As a student who is finds planning how i should spend my money a chore, I wish to have a Finance Adviser to help me plan my spending so that I don't have to do it myself, and it will be more accurate.

**Comment by LunarEclipz** [comment]
Acceptance Criteria :
1. Class attributes should include : Departments, Account balance, Planned Savings.
2. Departments have percentage which users can input and a pie chart to tell users the allocation of their money in relation to the percentage input in each department.
3. The Account balance is needed to form the pie chart. Where the departments are all part of the Account balance.
4. The planned savings is a small part of the departments where the user input the amount in which they plan to save. This also aids the finance adviser on how the money should be allocated.
