### ISSUE TITLE
Spending Log (Finance)

### ISSUE THREAD

**Issue by zyonwee** [LunarEclipz/OOPP-Slazz#5]

**Comment by LunarEclipz** [comment]
As a student who is always spending more then I planned at the start, I want to be able track why I have spent more then my budget. As such, I wish to be able to track which department was most of my money spent on.

**Comment by LunarEclipz** [comment]
Acceptance Criteria:
1. Class Attributes should consist of : Department, Item, Amount Spent.
2. The Department, Item And Amount Spent must be an input by the User. And can be manually altered.
3. For items in which user does not know which department it was spent on. Or the money that the User does not know where it went. It is labelled under the Department 'Unknown'.
